export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";
export const PRODUCT_DETALIS_REQUEST = "PRODUCT_DETALIS_REQUEST";
export const PRODUCT_DETALIS_SUCCESS = "PRODUCT_DETALIS_SUCCESS";
export const PRODUCT_DETALIS_FAIL = "PRODUCT_DETALIS_FAIL";
export const CLEAE_ALL_ERRORS = "CLEAE_ALL_ERRORS";